version: '2'
services:
  reverse-proxy:
    image: ipepe/traefik:1.7
    restart: always
    command: --acme.email="letsencrypt@example.org"
    networks:
      - traefik
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events

networks:
  traefik:
    external: true
